### ISSUE TITLE
Add 19300-3 back to the Opioid Drug Urine Screening Value Set

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/opioid-cds-r4#106]
Add this code back to the opioid-urine-drug-screening value set, it was removed to workaround an API issue (#67).

**Comment by sliver007** [comment]
This should not be done until we can confirm that it is no longer an issue. Specifically, we need to support the Opioid Pilots and until we know that this will not cause the issues that it caused initially, we should not restore it.

**Comment by c-schuler** [comment]
Verified the code has been restored in the ValueSet. In regards to pilot site issues, we will address on a case-by-case basis.
