### ISSUE TITLE
Regenerate ValueSets from current terminology spreadsheet.

### ISSUE THREAD

**Issue by sliver007** [cqframework/opioid-cds-r4#112]
The spreadsheet: https://docs.google.com/spreadsheets/d/1oU-LbcrOJUfOU4PjQp6yaHRWOQeRvjSDuxhsTvC8bLs/edit#gid=0

**Comment by sliver007** [comment]
Believe this is the tooling: https://github.com/cqframework/cqf-tooling/tree/opioid-terminology-generator

**Comment by bryantaustin13** [comment]
PR #121
