### ISSUE TITLE
Narrative templates for Library, PlanDefinition, and ActivityDefinition

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/opioid-cds-r4#124]
Update the IG to use the latest Library template: 
https://github.com/cqframework/sample-content-ig/blob/master/templates/liquid/Library.liquid

Add the new PlanDefinition template:
https://github.com/cqframework/sample-content-ig/blob/master/templates/liquid/PlanDefinition.liquid

Use the PlanDefinition template to develop an ActivityDefinition template.

**Comment by sliver007** [comment]
Added in GitHub #126
