### ISSUE TITLE
Value Set "Hospice Disposition" Not In opioid-cds-r4 IG

### ISSUE THREAD

**Issue by jorge-delagarza** [cqframework/opioid-cds-r4#137]
On line 37, OpioidCDSCommon.cql defines a value set "Hospice Disposition":
`valueset "Hospice Disposition": 'http://fhir.org/guides/cdc/opioid-cds/ValueSet/hospice-disposition' // Harvested from VSAC - OID: 2.16.840.1.113762.1.4.1108.15`
([Link](https://github.com/cqframework/opioid-cds-r4/blob/2547ea62b97bc8d8302ccbe424ad91848a157e9d/input/pagecontent/cql/OpioidCDSCommon.cql))
This value set does not appear to be defined in the opioid-cds-r4 IG, neither in the "vocabulary" folder:
https://github.com/cqframework/opioid-cds-r4/tree/master/input/vocabulary/valueset
Nor in the terminology Bundle:
https://github.com/cqframework/opioid-cds-r4/blob/2ab0706146644666287a93050b36a4c11ca77833/input/pagecontent/quick-start-bundles/opioid-cds-terminology-bundle.json
It is, however, defined in the STU3 version of the IG:
https://github.com/cqframework/opioid-cds/blob/master/input/vocabulary/valueset/valueset-discharge-to-hospice.json

I notice that the content of the ValueSet in the STU3 IG seems to be the same as the "discharge-to-hospice" ValueSet in the R4 IG:
https://github.com/cqframework/opioid-cds-r4/blob/master/input/vocabulary/valueset/valueset-discharge-to-hospice.xml
Which has url="http://fhir.org/guides/cdc/opioid-cds/ValueSet/discharge-to-hospice"

So it seems that either OpioidCDSCommon.cql needs to be updated to match the URL in the "discharge-to-hospice" ValueSet, or the ValueSet needs to be updated to match the URL in OpioidCDSCommon.cql

**Comment by c-schuler** [comment]
This ValueSet is present on both master and v2016 branched
