### ISSUE TITLE
Add CQL syntax highlighting to generated narratives

### ISSUE THREAD

**Issue by c-schuler** [cqframework/opioid-cds-r4#194]
The generated narratives with CQL content would be more readable with syntax highlighting. 

[Example](https://build.fhir.org/ig/HL7/cqf-measures/Library-BCSComponent.html#cql-content)

The example above uses SQL syntax highlighting which is good enough, but not ideal. An ideal solution would be to use the actual CQL grammar in a JavaScript library. An example of that can be found in the [CQL specification](https://github.com/HL7/cql/blob/master/spec/dist/cql.js).

**Comment by alackerbauer** [comment]
@1anja1 took on this task, we will push this together later today and it should be ready for review soon. 

![Image](https://user-images.githubusercontent.com/33912849/231771535-8fcab547-297b-4066-99ff-68f29f3542b6.png)

**Comment by 1anja1** [comment]
merge request #320
