### ISSUE TITLE
Update Guideline Name in Service Alerts

### ISSUE THREAD

**Issue by gregoryawhite** [cqframework/opioid-cds-r4#207]
CDS service alerts include the Guideline name as the source of the alert's guidance. Alerts also provide a link to the Guideline. For artifacts that implement the 2016 Guideline, please update the source and link to read "CDC 2016 Guideline for Prescribing Opioids for Chronic Pain". This addition is needed to clarify for users what version of the Guideline the alert is representing as well as the version the link opens. Note the Guideline title capitalization in the quotes above as well as the addition 2016.

**Comment by c-schuler** [comment]
Verified the guideline version has been updated in the alerts

**Comment by gregoryawhite** [comment]
Thanks Chris!

**Comment by gregoryawhite** [comment]
Closing this with thanks
