### ISSUE TITLE
Add trigger diagram narrative

### ISSUE THREAD

**Issue by gregoryawhite** [cqframework/opioid-cds-r4#208]
Consider adding a narrative explanation below the trigger overview diagram on the home page section 1.4. Example narrative "Orange shapes represent preferred trigger approaches. Items with clear/white centers are available (developed in earlier pilot testing prior to EHR support for order based hooks) for implementation at sites without preferred trigger capabilities in existing software for CDS Hooks."

**Comment by c-schuler** [comment]
Start on 2016

**Comment by c-schuler** [comment]
Resolved by #311 and #314
