### ISSUE TITLE
Document Data Roller Functionality

### ISSUE THREAD

**Issue by gregoryawhite** [cqframework/opioid-cds-r4#210]
Add information about how to utilize the data roller to refresh test data to the repo's "read me" narrative

**Comment by alackerbauer** [comment]
Done but need to double check the english before I put into review: https://github.com/cqframework/opioid-cds-r4/tree/210-data-roller-functionality#local-testing-and-the-data-roller

I described a bit further about local testing to describe why this is needed in the first place.

**Comment by alackerbauer** [comment]
merge request: https://github.com/cqframework/opioid-cds-r4/pull/319
