### ISSUE TITLE
Feedback on the versioning diagram

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/opioid-cds-r4#216]
Would be good to explain the significance of the minor and patch versions:

* major: Guideline version
* minor: New features and capabilities, but not breaking changes
* patch: Bug fixes and technical corrections.

Would be good to illustrate that in the diagram with a 2022-Fix branch and 2016-Fix branch showing the version increment

**Comment by brynrhodes** [comment]
Would also be good to illustrate the publishing aspect, where some nominated tag is published on fhir.org
Would also be good to discuss the difference between draft and active status

**Comment by brynrhodes** [comment]
For 2022, the IG and all the artifacts in it are "draft" status.
For 2016,, the IG is active, and any artifact we have pilot experience with is "active", all the rest are "draft"

**Comment by bryantaustin13** [comment]
The first one in this list - the diagram and the 3rd one (draft vs active) are both answered in #218. Others forthcoming.
