### ISSUE TITLE
Additional feedback on the version diagram

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/opioid-cds-r4#228]
Current diagram has versioning as:

v2022.0.1 - v2022.1.0 - v2022.1.1

v2016.0.1 - v2016.1.0 - v2016.1.1

This is confusing because minor versions typically don't start at 0, we should update to:

v2022.1.0 - v2022.2.0 - v2022.2.1

v2016.1.0 - v2016.2.0 - v2016.2.1

**Comment by bryantaustin13** [comment]
PR https://github.com/cqframework/opioid-cds-r4/pull/271#issue-1473189462
