### ISSUE TITLE
Address outstanding QA warnings in 2016 IG

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/opioid-cds-r4#261]
Address outstanding QA warnings in 2016 IG. If a warning is not addressable, document it in the suppressed messages file.

Specific messages that should be addressed are:
* For all value sets: Rule vsd-0: 'Name should be usable as an identifier for the module by machine processing applications such as code generation' Failed (Note this should be addressed as part of the automated ValueSet generation process)
* The value set import http://fhir.org/guides/cdc/opioid-cds/ValueSet/non-opioid-illicit-drug-urine-screening could not be found so cannot be checked
* The ShareableValueSet profile says that the experimental element is mandatory, but it is not present. Published value sets SHOULD conform to the ShareableValueSet profile
* All the warnings about markdown content: The markdown contains content that appears to be an embedded HTML tag starting at 'ht'. This will (or SHOULD) be escaped by the presentation layer. The content should be checked to confirm that this is the desired behaviour
* Attachments have data and/or url, or else SHOULD have either contentType and/or language
* The display "Medical Oncology" is not a valid display for the code {http://nucc.org/provider-taxonomy}207RX0202X - should be one of ['Medical Oncology Physician'] (from http://tx.fhir.org/r4) for 'http://nucc.org/provider-taxonomy#207RX0202X'
* None of the codings provided are in the value set 'Practice Setting Code Value Set' (http://hl7.org/fhir/ValueSet/c80-practice-codes), and a coding is recommended to come from this value set) (codes = http://nucc.org/provider-taxonomy#207RX0202X)
* None of the codings provided are in the value set 'Medication dispense category codes' (http://hl7.org/fhir/ValueSet/medicationdispense-category), and a coding is recommended to come from this value set) (codes = http://terminology.hl7.org/CodeSystem/medicationrequest-category#community)
* Code System URI 'http://www.ama-assn.org/go/cpt' is unknown so the code cannot be validated (understood that it's a CPT code, but needs to be added to the suppressed warnings with that explanation)
* The HTML fragment 'globals-table.xhtml' is not included anywhere in the produced implementation guide (seek guidance on IG Creation)
* The issues related to IG dependency canonicals: The correct canonical URL for this dependency is http://hl7.org/fhir/uv/cpg/ImplementationGuide/hl7.fhir.uv.cpg
* The issues related to descriptions: Unable to find ImplementationGuide.definition.resource.description for the resource Library/OMTKData2019. Descriptions are strongly encouraged if they cannot be inferred from the resource to allow proper population of the artifact list.

**Comment by Capt-Mac** [comment]
unable to locate these errors:

The HTML fragment 'globals-table.xhtml' is not included anywhere in the produced implementation guide (seek guidance on IG Creation)

The ShareableValueSet profile says that the experimental element is mandatory, but it is not present. Published value sets SHOULD conform to the ShareableValueSet profile
