### ISSUE TITLE
Update 2022 Guideline Name in 2022 IG

### ISSUE THREAD

**Issue by gregoryawhite** [cqframework/opioid-cds-r4#265]
Please note that name of the 2022 Guideline is different than the name of the 2016 Guideline. The 2022 Guideline name is “CDC Clinical Practice Guideline for Prescribing Opioids for Pain”. The 2022 IG currently references it as “CDC 2022 guideline for prescribing opioids for subacute or chronic pain”. Please use either “CDC 2022 Clinical Practice Guideline for Prescribing Opioids for Pain” or, for abbreviated references, use “CDC 2022 Clinical Practice Guideline”. This name change is important because the 2016 version focuses on treatment for chronic pain, while the 2022 version is broader and includes guidance for all pain categories.

**Comment by c-schuler** [comment]
Replaced by #276
