### ISSUE TITLE
Define profiles for data elements

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/opioid-cds-r4#267]
For each data element, identify the profile (a US Core, or US Core-derived profile) that should be used to characterize the data element.

The data requirements analysis of the CQL should also be used to help determine these profile requirements.

**Comment by alackerbauer** [comment]
Reminder to @alackerbauer to clarify what to do (stand up meeting):

The data elements are described with the usage of tables within the IG, e.g. here: https://build.fhir.org/ig/cqframework/opioid-cds-r4/recommendation-01.html

This table should be extended by 2 columns: (1) the profile used and (2) the path used

**Comment by alackerbauer** [comment]
where is the best place to look up CQL-->FHIR logic?

e.g. I am aware of what this is resolved to and where the values come from to perform this retrieve by value set:`[Encounter: Common."Office Visit"] Encounter` ...but I do not know where to look up best what exact element of `Encounter` is used for resolving that. I am assuming it is `encounterType` but can't be sure about it without checking somewhere in the code.

**Comment by alackerbauer** [comment]
done for first 2 sub routines. screenshot for quick sanity check if that is what we are aiming for:

<img width="1137" alt="Screenshot 2023-04-04 at 11 23 13" src="https://user-images.githubusercontent.com/33912849/229748011-bdfc6e1b-d9c7-49d4-bb3c-93026295156b.png">

**Comment by c-schuler** [comment]
Resolved by #318
