### ISSUE TITLE
Add description of evidence type and recommendation strength

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/opioid-cds-r4#268]
The 2016 Opioid Prescribing Guideline establishes recommendation category and evidence type for each recommendation, and provides definitions and explanatory text for the categorization and meaning of each evidence type. Provide links from the recommendation category and evidence type in each recommendation to a discussion of those summarizing (and linking directly to) the discussion in the guideline.

Also ensure the extensions for each recommendation correctly reflect the ratings from the guideline.

**Comment by alackerbauer** [comment]
I checked the documentation (page content) for each recommendation and it correctly reflects the guideline. I also looked at the according plandefinitions and found that recommendation 9 had an incorrect evidence type (assuming the most obvious mapping, which seems to be followed by all other recommendations):

# Recommendation Strength
| HL7 Terminology      | CDC Guideline |
| ----------- | ----------- |
| Strong      | A       |
| Weak   | B        |

# Evidence Type
| HL7 Terminology      | CDC Guideline |
| ----------- | ----------- |
| High      | 1      |
| Moderate   | 2       |
| Low      | 3       |
| Very Low   | 4       |

**Comment by alackerbauer** [comment]
I am happy to include the link to the summary https://www.cdc.gov/mmwr/volumes/65/rr/rr6501e1.htm#B2_down to the IG documentation. First we need to clarify 2 issues:
1) the current v2016 version isn't successfully building the IG (or I am doing something wrong, _genonce on master works just fine, but not on v2016).
2) do we want to include a separate page within the IG for this or should it just be a direct link to the cdc guideline?

**Comment by alackerbauer** [comment]
merge request: https://github.com/cqframework/opioid-cds-r4/pull/310

**Comment by alackerbauer** [comment]
merge request #313 
--> please clarify what to do with mixed evidence types for rec#4 & rec#5 (see description in merge request).

**Comment by c-schuler** [comment]
Resolved by #313
