### ISSUE TITLE
Apply CDC pre-publication feedback to 2016 IG

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/opioid-cds-r4#276]
Update links to MME cautionary langusage in recommendations 5, 8, and 12 to a new section in the IG containing the updated cautionary language in the comment below. Use the cautionary language at the following link as the starting point:

https://fhir.org/guides/cdc/opioid-mme-r4/mme-calculator.html#cautions

CDC has removed “prescribing” for “2016 CDC Prescribing Guideline”. There are some legal reasons for this change. The updated nomenclature is “2016 CDC Guideline”. They would like you to make this change throughout the IG. I would think that includes the reference to the 2016 Guideline as a source in the CDS alerts and the link to the Guideline in the alerts. Note that this is only a change to the "short name" of the guideline when it is referenced multiple times in text. The full name is still “2016 CDC Guideline for Prescribing Opioids for Chronic Pain”
 
Regarding their proposed changes to the version management box at the top of the IG (see the attachment I forwarded earlier), I explained to them that it is created by the publisher and there may be some limitations implementing their proposed edits. They requested that where their updates  cannot be added to the box, for example if you can not add a link to the 2022 Guideline, that content is added to the IG in prominent location below the version box. (This will be handled by the name change to the IG, the content in the publish box is handled by the publisher)
 

They have provided CDC reviewed and approved text about the 2022 Guideline in a second attachment. We recently posted this language the project’s confluence page. I think their intention is to provide some preapproved text about the 2022 Clinical Practice Guideline should you be able to use some of it when referencing and linking to the 2022 Guideline. My impression is that they want it to be clear to IG users that
 
Add a note to the intro section of the IG to state:
This IG is implementing the 2016 Guideline, there is now a 2022 Guideline “2022 Clinical Practice Guideline” and where it can be access online (link to the 2022 published guideline)

**Comment by c-schuler** [comment]
Updated cautionary language:

> Please edit the third bullet to read “Tapentadol is a mu-opioid receptor agonist and norepinephrine reuptake inhibitor. MMEs are based on the degree of mu-opioid receptor agonist activity, but it is unknown if this drug is associated with overdose in the same dose-dependent manner as observed with medications that are solely mu-opioid receptor agonists.” Changes are highlighted in yellow.
> 
> Also, as we discussed earlier about the revised MME table. We need to make sure that the edits to the Table are revised here too. “Of note for the extra caution, In the 2022 CDC Clinical Practice Guideline for Prescribing Opioids for pain, there are not graduated methadone conversion factors depending on the daily dosage. The conversion factor for methadone is 4.7 regardless of methadone dosage.”

**Comment by c-schuler** [comment]
Addressed in #278 and #279
