### ISSUE TITLE
Use CDC preferred naming conventions for the 2022 Guideline within 2022 IG

### ISSUE THREAD

**Issue by gregoryawhite** [cqframework/opioid-cds-r4#312]
Please refer to the 2022 Guideline within the 2022 R4 IG using these naming conventions:

Full Name: 2022 CDC Clinical Practice Guideline for Prescribing Opioids for Pain

Short Name: 2022 CDC Clinical Practice Guideline

**Comment by alackerbauer** [comment]
should drafts be updated to the official link and also then follow naming conventions? e.g. here: https://github.com/cqframework/opioid-cds-r4/blob/master/input/pagecontent/recommendation-01.xml#L3

**Comment by gregoryawhite** [comment]
Yes, please, we should remove links to the draft Guideline and add links to the finalized 2022 Guideline. 

For example, for recommendation 1 we could point to Recommendation 1 with this link https://www.cdc.gov/mmwr/volumes/71https://www.cdc.gov/mmwr/volumes/71/rr/rr7103a1.htm#:~:text=lasting%20%3E3%20months%5D.)-,Recommendation%201,-

or if it is better just to point to whole guideline just use https://www.cdc.gov/mmwr/volumes/71/rr/rr7103a1.htm 

Thank You

**Comment by alackerbauer** [comment]
resolved merge conflicts: https://github.com/cqframework/opioid-cds-r4/pull/316
