### ISSUE TITLE
Recommendation Category and Evidence Type Links

### ISSUE THREAD

**Issue by gregoryawhite** [cqframework/opioid-cds-r4#321]
The link to recommendation category and evidence type, used at the end of each recommendation statement, appears to take the user to the top of Box 3 in the Guideline. The immediate content in Box 3 is the list of the 12 recommendations clustered by general themes. Below this is an explanation of the recommendation category and evidence type means. 
If practical, consider using more direct links such as:
recommendation category 
https://www.cdc.gov/mmwr/volumes/71/rr/rr7103a1.htm#:~:text=evidence%20type%3A%201).-,Recommendation%20categories,-(on%20basis%20of
evidence type - 
https://www.cdc.gov/mmwr/volumes/71/rr/rr7103a1.htm#:~:text=specific%20clinical%20situations.-,Evidence%20types,-(on%20basis%20of

**Comment by alackerbauer** [comment]
mr: https://github.com/cqframework/opioid-cds-r4/pull/324

**Comment by c-schuler** [comment]
Resolved by #324
