### ISSUE TITLE
Recommendation 12 section 26.0.1.1

### ISSUE THREAD

**Issue by gregoryawhite** [cqframework/opioid-cds-r4#322]
Recommendation 12 section 26.0.1.1 “Rationale for Medication-Assisted Treatment or Behavioral Therapy” may be legacy content. Note that the 2022 Recommendation 12 statement is focused on pharmacological therapy, not behavioral therapy and that Recommendation 12 condition logic does not include evaluations for daily MME or UDS results. Consider either updating or removing this section.

**Comment by alackerbauer** [comment]
updated to current CQL expression's content
<img width="1145" alt="Screenshot 2023-04-20 at 10 23 03" src="https://user-images.githubusercontent.com/33912849/233305854-5c9f1188-e493-4a88-a5b7-497ff572b23e.png">

**Comment by alackerbauer** [comment]
mr #326

**Comment by gregoryawhite** [comment]
Thanks for speedy update. Thinking that a review is an internal Smile process? Chris if you need or want me involved, just let me know.

**Comment by c-schuler** [comment]
Resolved by #326. @gregoryawhite feel free to reopen this if the update isn't satisfactory.
