### ISSUE TITLE
Functional Descriptions Refinements

### ISSUE THREAD

**Issue by gregoryawhite** [cqframework/opioid-cds-r4#323]
Recommendations 1, 3
From Functional Description – Opioid Naïve 
•	Currently reads – “No indication of opioid use in the past 90 days from a prescription, self report, or a dispensing event”. The service does not currently review self-reported or dispensed information, so thinking self-reported and dispensed medications should be removed from this functional statement until they are implemented in the service. Alternately, “for future implementation” could be added in parentheses “self-report (for future implementation)” “dispensing event (for future implementation) 

Recommendations 2, 7, 10 
Functional Description – Subacute or Chronic Pain
•	Do we want to provide a condition or a link to a condition statement for this Functional Description statement? “Prescription is for treating subacute and/or chronic pain.”
For example, 
o	Prescription is for treating subacute and/or chronic pain
        	 Order for opioid analgesic with an expected supply duration equal to, or greater than, 28 days

Recommendation 8
Add an “or” next to these conditions. For example:
•	Factors that increase risk for opioid overdose are present:
       o	 Currently receiving benzodiazepine or other central nervous system depressant medications, or
       o	 High opioid dosages (MME/day >= 50), or
       o	 History of substance use disorder, or
       o	 Diagnosed with sleep-disordered breathing condition

**Comment by alackerbauer** [comment]
mr: https://github.com/cqframework/opioid-cds-r4/pull/325

also added point 1 to recommendation 2.

**Comment by c-schuler** [comment]
Resolved in #323
