### ISSUE TITLE
Decision points for Chronic Pain

### ISSUE THREAD

**Issue by gtoups** [cqframework/opioid-cds-r4#47]
Page: http://build.fhir.org/ig/cqframework/opioid-cds/process-documentation.html
Section: 8.1.3 under Chronic Pain, says: "_TODO - the decision points for this criteria are not well defined._"
Need to define the decision points for this criteria.

**Comment by brynrhodes** [comment]
Add decision point documentation and subroutines to support identification and configuration of chronic and acute pain throughout.

For Chronic Pain
A medication is considered for chronic pain if it is being prescribed for 28 days or more or the patient is chronically on opioids

For Acute Pain
A medication is considered for acute pain if it is being prescribed for less than 28 days or the patient is not chronically on opioids

Chronically On Opioids
A patient is considered chronically on opioids if they have been on opioids for either
1) 7 or more of the past 10 days with an encounter
2) 21 or more of 30 days for each of the past 3 months

Include For Chronic Pain in the inclusion criteria for each recommendation except Rec#6
Include For Acute Pain in the inclusion criteria for recommendation Rec#6

**Comment by brynrhodes** [comment]
Chronic Pain Decision Documentation:
Determining whether a patient is being prescribed opioids for chronic pain is difficult to determine by examination of the medical record alone. The project team identified the following proxies for chronic pain, used throughout the recommendations:

1. A medication is considered for chronic pain if it is being prescribed for 28 days or more, or the patient is chronically on opioids

2. A medication is considered for acute pain if it is being prescribed for less than 28 days or the patient is not chronically on opioids

Chronically on opioids is determined as a patient meeting either of the following criteria:
1. Patient has been prescribed opioids for 7 or more of the past 10 days with an encounter
2. Patient has been prescribed opioids for 21 or more of 30 days for each of the past 3 months

Whether to use Chronically on opioids as an additional indication for chronic pain is introduced as a configuration option, defaulted to "on".

**Comment by c-schuler** [comment]
Chronically on opioid docs not needed.

Chronic pain docs added.
