### ISSUE TITLE
Create Opioid Logic implementation guide

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/opioid-cds-r4#48]
Create a library and implementation guide that supports the FHIR-version-independent calculation of Morphine Milligram Equivalents.

**Comment by brynrhodes** [comment]
Substantially complete in http://build.fhir.org/ig/cqframework/opioid-mme-r4

**Comment by brynrhodes** [comment]
Only thing left on this task is to refactor Recommendations #05 and #08 to use the MME R4 IG

**Comment by c-schuler** [comment]
Opioid MME IG has been created. Follow-up task captured by #107
