### ISSUE TITLE
U of U: Deliver and develop content and ruler

### ISSUE THREAD

**Issue by SeanWheelwright** [cqframework/opioid-cds-r4#67]
Should include ruler logging and resolve retrieve bug

**Comment by sliver007** [comment]
Worked with folks at the U of U to update content and test on 6/10/2020. After updating content we were able to confirm that the logging was working, the problematic LOINC code 19300-3 was no longer being included in the queries to the fhir server after explicitly excluding it in the 'Opioid Drug Urine Screening' valueset - it had been resulting in 1000s of duplicate lab|Observation results. We were ultimately able to get successful tests for both Recommendations 10 & 11 patient-view. One issue worth noting that was re-discovered that had  been encountered in the past:
When a patient is detected as being inpatient by Epic, Epic has kindly set up its FHIR server so it will completely ignore all non-inpatient medications.  Perhaps they thought FHIR clients would not be checking the medication categories, and so it was safer to not send out any others.
