### ISSUE TITLE
Change Recommendation #4 Title - avoid use of "Rate"

### ISSUE THREAD

**Issue by SeanWheelwright** [cqframework/opioid-cds-r4#74]
Avoid the use of the term "rate" in the discussion

**Comment by sliver007** [comment]
This is the "Title" property of the Page in the Implementation Guide resource (opioid-cds.xml). Change it to "Recommendation #4 - Opioid Immediate Release Form When Starting Opioid Therapy".

**Comment by sliver007** [comment]
The output can be viewed in the main page header here: http://build.fhir.org/ig/cqframework/opioid-cds-r4/branches/develop/recommendation-04.html

**Comment by sliver007** [comment]
Resolved in GH#de2e960ad67e24cec0aa6f5109c7f5eb00338a24
