### ISSUE TITLE
Incorrect use of Substance Abuse Behavior Counseling value set

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/opioid-cds-r4#83]
The reference to the Substance Abuse Behavior Counseling value set should use Procedure, not Condition:

https://github.com/cqframework/opioid-cds-r4/blob/master/input/pagecontent/cql/OpioidCDSREC08.cql#L90

**Comment by sliver007** [comment]
Resolved in GH# cec89cae6c5f3ebef685da99296e4ac43a293abc
