### ISSUE TITLE
Create narrative template for value sets

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/opioid-cds-r4#98]
The default narrative for value sets does not include the information for the publishable, computable, or executable profiles. Would be good to have a template for this, and to include that template in the CPG-IG.

**Comment by sliver007** [comment]
We need to think more about this. Also, this is low priority.

**Comment by c-schuler** [comment]
Recommend adding sections by extension url (e.g. "resource-approvalDate" or "valueset-effectiveDate") to the ValueSet narrative table with the appropriate listed extension type value.

**Comment by alackerbauer** [comment]
more details at FHIR Liquid Profile: https://confluence.hl7.org/display/FHIR/FHIR+Liquid+Profile

**Comment by alackerbauer** [comment]
for the rules text, the value set element indicates the content is markdown. but it isn't really markdown. also we don't yet support markdown rendering within the html tags. what would be the best way of showing the rules text contnet?

![Image](https://user-images.githubusercontent.com/33912849/232730600-5d1da87e-94bf-4417-b9f4-b4eece0b8d8b.png)

**Comment by alackerbauer** [comment]
I am having trouble with the layout, since the liquid file definition for ValueSet will overwrite the default narrative that contains important information. There are 2 different headers (CLD and Expansion) and both should be available and contain separate information. It would be great to know how e.g. this is being resolved: https://github.com/HL7/fhir/blob/master/tools/templates/template-vs-ig.html#L26

**Comment by alackerbauer** [comment]
added my question to chat.fhir.org: https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Extensions.20in.20Narrative.20.28ValueSet.29

**Comment by alackerbauer** [comment]
the question lead to a new thread in #terminology, asking about the reasoning behind the structure of our value set (compose vs expand). is there any input on what I should respond there? https://chat.fhir.org/#narrow/stream/179202-terminology/topic/Valueset.20Narrative.3A.20Adding.20Extensions also, there was some feedback on where to put the RxNorm versioning.
